# Generated by Django 3.0 on 2019-12-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfilename', models.CharField(max_length=200)),
                ('myfile', models.FileField(upload_to='assignments/uploads/')),
                ('myencryption', models.CharField(max_length=200)),
            ],
        ),
    ]
