# Generated by Django 3.0 on 2019-12-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignments', '0003_auto_20191214_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='myfile',
            field=models.FileField(upload_to='asignments/uploads/'),
        ),
    ]
