# Generated by Django 3.0 on 2019-12-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignments', '0004_auto_20191214_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='myencryption',
            field=models.TextField(),
        ),
    ]
