# Generated by Django 3.0 on 2019-12-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignments', '0005_auto_20191214_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='myencryption',
            field=models.CharField(max_length=1500),
        ),
    ]
